echo "Hello World in Linux Bash"
echo "Another command to execute but its only Hello World"
echo "authentication was removed"
echo "authentication succeeded"
echo "credentials saved"
echo "makefile added"
echo "another echo print"
echo "saved"
